name: CI for TutorialsPoint Tests

on: push

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '18'

       # Build with Maven
      - name: Build with Maven
        run: mvn clean compile

       # Running tests via testng.xml
      - name: Run tests with testng.xml
        run: mvn test -Dsurefire.suiteXmlFiles=src/test/resources/runner/testng.xml
